## 类和实例


In [1]:
class Animal(object):
    pass

In [2]:
class Animal(object):
    def __init__(self, name):
        self.name = name

In [3]:
animal = Animal('dog')
animal2 = Animal('dog2') 

In [4]:
print(animal2.name)

dog2


In [5]:
class Animal(object):
    def __init__(self, name):
        self.name1 = name
    def greet(self):
        print ('Hello, I am %s.' % self.name1)

In [6]:
dog1 = Animal('dog1')

In [7]:
dog1.name1

'dog1'

In [8]:
dog1.greet()

Hello, I am dog1.


### 访问限制

In [9]:
class Animal(object):
    def __init__(self, name):
        self.__name = name
    def greet(self):
        print ('Hello, I am %s.' % self.__name)

In [10]:
dog1 = Animal('dog1')

In [11]:
dog1.__name

AttributeError: 'Animal' object has no attribute '__name'

In [12]:
dog1.greet()

Hello, I am dog1.


### 继承

In [13]:
class Animal(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print ('Hello, I am %s.' % self.name)

In [14]:
class Dog(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print('WangWang.., I am %s.' % self.name)

In [15]:
dog2 = Dog('dog2')
#print(dog2.name)
dog2.greet()

WangWang.., I am dog2.


In [16]:
class Animal(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print ('Hello, I am %s.' % self.name)
        
class Dog(Animal):
    def greet(self):
        print ('WangWang.., I am %s. ' % self.name)

In [17]:
dog3 = Dog('dog3')
# print(dog3.name)
dog3.greet()

WangWang.., I am dog3. 


In [18]:
class Dog(Animal):
    def greet(self):
        print ('WangWang.., I am %s. ' % self.name)
    def run(self):
        print ('I am running.I am running')

In [19]:
dog3 = Dog('dog3')
print(dog3.name)
dog3.greet()

dog3
WangWang.., I am dog3. 


In [20]:
dog3.run()

I am running.I am running


### super 用法

In [21]:
class Animal(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print ('Hello, I am %s.' % self.name)

class Dog(Animal):
    def greet(self):
        super(Dog, self).greet()   
        print ('WangWang...')

In [22]:
dog = Dog('dog')

In [23]:
dog.greet()

Hello, I am dog.
WangWang...


In [24]:
class Base(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def show(self):
        print('(a,b) is (%d, %d)' % (self.a, self.b))

class A(Base):
    def __init__(self, a, b, c):
        super(A, self).__init__(a, b)  # Python3 可使用 super().__init__(a, b)
#         self.a = a
#         self.b = b
        self.c = c
    def show(self):
        print('(a,b,c) is (%d, %d, %d)' % (self.a, self.b, self.c))

In [25]:
x = Base(2,3)

In [26]:
x.show()

(a,b) is (2, 3)


In [27]:
y = A(1,3,4)
y.show()

(a,b,c) is (1, 3, 4)


In [28]:
import numpy as np

In [29]:
a = np.random.randn(4,4)

In [30]:
a

array([[-0.60961724, -1.56778828,  0.81029824, -0.48965804],
       [-0.40991897,  0.15437088,  0.0689699 ,  0.02545634],
       [-0.67101015, -1.21325407,  1.08276906,  1.39602506],
       [-1.88201444,  0.69232501,  1.87925649, -0.36080322]])

In [31]:
b = a.reshape(2,2,2,2)

In [32]:
c = b.transpose(0,2,1,3)

In [33]:
c

array([[[[-0.60961724, -1.56778828],
         [-0.40991897,  0.15437088]],

        [[ 0.81029824, -0.48965804],
         [ 0.0689699 ,  0.02545634]]],


       [[[-0.67101015, -1.21325407],
         [-1.88201444,  0.69232501]],

        [[ 1.08276906,  1.39602506],
         [ 1.87925649, -0.36080322]]]])

In [34]:
d = c.reshape(4,2,2)

In [35]:
d[0]

array([[-0.60961724, -1.56778828],
       [-0.40991897,  0.15437088]])

In [36]:
d[1]

array([[ 0.81029824, -0.48965804],
       [ 0.0689699 ,  0.02545634]])

In [37]:
a = np.random.rand(2,2)

In [38]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
a.shape

(3, 3)

In [40]:
a.squeeze().shape

(3, 3)

In [41]:
b = np.pad(a,(3,3),'symmetric')

In [42]:
b.shape

(9, 9)

In [43]:
b

array([[9, 8, 7, 7, 8, 9, 9, 8, 7],
       [6, 5, 4, 4, 5, 6, 6, 5, 4],
       [3, 2, 1, 1, 2, 3, 3, 2, 1],
       [3, 2, 1, 1, 2, 3, 3, 2, 1],
       [6, 5, 4, 4, 5, 6, 6, 5, 4],
       [9, 8, 7, 7, 8, 9, 9, 8, 7],
       [9, 8, 7, 7, 8, 9, 9, 8, 7],
       [6, 5, 4, 4, 5, 6, 6, 5, 4],
       [3, 2, 1, 1, 2, 3, 3, 2, 1]])

In [44]:
np.random.randn(*a)

TypeError: only integer scalar arrays can be converted to a scalar index

In [45]:
a = np.expand_dims(a, 0)

In [46]:
a.shape

(1, 3, 3)

In [47]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [49]:
a = np.zeros((1,2,3))

In [50]:
np.random.randint(5)

3

In [51]:
import torch

In [52]:
a = torch.randn(3,1)

In [53]:
a

tensor([[ 0.8963],
        [-1.3225],
        [-0.2706]])

In [54]:
b = torch.randn(4,1)

In [55]:
b

tensor([[ 0.2817],
        [-1.1071],
        [-1.6868],
        [-0.4115]])

In [56]:
X = torch.randn(3,4,requires_grad=True)

In [57]:
X

tensor([[ 0.7660,  0.3220, -0.8447,  0.4240],
        [-1.2749, -0.5322,  0.0022,  0.9842],
        [ 0.1563,  0.3853, -1.0268, -1.7529]], requires_grad=True)

In [58]:
y = torch.mm(torch.mm(a.transpose(1,0), X), b)

In [59]:
y

tensor([[0.6705]], grad_fn=<MmBackward>)

In [60]:
y = torch.mm(torch.mm(a.t(), X), b)

In [61]:
y

tensor([[0.6705]], grad_fn=<MmBackward>)

In [62]:
from torch import autograd
grads = autograd.grad(y, X)

In [63]:
print(grads)

(tensor([[ 0.2525, -0.9923, -1.5119, -0.3688],
        [-0.3726,  1.4642,  2.2309,  0.5442],
        [-0.0762,  0.2996,  0.4565,  0.1114]]),)


In [64]:
print(torch.mm(a, b.t()))

tensor([[ 0.2525, -0.9923, -1.5119, -0.3688],
        [-0.3726,  1.4642,  2.2309,  0.5442],
        [-0.0762,  0.2996,  0.4565,  0.1114]])


In [65]:
grads = autograd.grad(y, a)

RuntimeError: One of the differentiated Tensors does not require grad

In [66]:
print(a.requires_grad)

False


In [67]:
print(X.requires_grad)

True


In [68]:
a.dtype

torch.float32