In [1]:
import torch
print(torch.__version__)

1.0.1


### 自动求导机制

In [2]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[-1.4021],
        [-0.3113],
        [-0.4544],
        [ 0.0270]], requires_grad=True)
tensor([[ 0.5766],
        [-0.4754],
        [-1.6159],
        [-0.1954]], requires_grad=True)
tensor([[ 0.7930, -1.4101,  0.2655, -0.1764],
        [ 0.2612, -0.2323,  0.9492,  1.4831],
        [-1.6547, -1.7608,  0.2552,  0.2799],
        [-0.9223,  0.6974,  0.1540, -2.5709]])


In [3]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[-0.2927]], grad_fn=<MmBackward>)


In [4]:
z = x.t().mm(W).mm(y).abs()
print(z)

tensor([[0.2927]], grad_fn=<AbsBackward>)


In [5]:
print(x.grad)

None


In [6]:
z.backward()

In [7]:
print(x.grad)

tensor([[-0.7332],
        [ 1.5627],
        [ 0.5841],
        [ 0.6099]])


In [8]:
print(W.mm(y))

tensor([[ 0.7332],
        [-1.5627],
        [-0.5841],
        [-0.6099]], grad_fn=<MmBackward>)


### 默认情况下，定义的tensor属性requires_grad为false

In [9]:
x = torch.randn(4,1)
print(x)
y = torch.mm(torch.t(x),x)
y.backward()

tensor([[ 0.9805],
        [-0.9318],
        [ 1.2752],
        [-0.3978]])


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [10]:
print(y)

print(x.grad)

print(2*x)

tensor([[3.6140]])
None
tensor([[ 1.9610],
        [-1.8637],
        [ 2.5504],
        [-0.7956]])


### PyTorch Tensor 与 Numpy 转换

In [11]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

[[ 1.45880995  0.47774089  0.62343626 -1.2435258 ]
 [ 0.76167892 -1.56733751  1.07843755 -2.53177271]
 [-0.05841124  0.08013339  1.24128386 -0.34289038]]
<class 'numpy.ndarray'>


In [12]:
a_tensor = torch.from_numpy(a)
print(a_tensor)
print(type(a_tensor))

tensor([[ 1.4588,  0.4777,  0.6234, -1.2435],
        [ 0.7617, -1.5673,  1.0784, -2.5318],
        [-0.0584,  0.0801,  1.2413, -0.3429]], dtype=torch.float64)
<class 'torch.Tensor'>


In [13]:
b = a_tensor.numpy()
print(b)
print(type(b))

[[ 1.45880995  0.47774089  0.62343626 -1.2435258 ]
 [ 0.76167892 -1.56733751  1.07843755 -2.53177271]
 [-0.05841124  0.08013339  1.24128386 -0.34289038]]
<class 'numpy.ndarray'>


In [14]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

[[-1.0431812   0.51011384 -0.3059487   0.62423646]
 [ 1.1348357   1.042794    0.07714036 -0.5081506 ]
 [ 1.0512929   0.15754318  0.00497111  1.3634368 ]]
<class 'numpy.ndarray'>


In [15]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [16]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))

[[ 2.4672408   0.8750605  -0.29466197  1.2262601 ]
 [ 0.9036353   0.5309001  -0.16697964 -0.24023901]
 [-1.131194    1.5241777   1.7031705  -0.97473276]]
tensor([[ 2.4672,  0.8751, -0.2947,  1.2263],
        [ 0.9036,  0.5309, -0.1670, -0.2402],
        [-1.1312,  1.5242,  1.7032, -0.9747]])
<class 'numpy.ndarray'>
